### ISSUE TITLE
Some dates not working

### ISSUE THREAD

**Issue by vnmabus** [apiforfun/theforexapi#5]
Some dates are not working. For example:
https://theforexapi.com/api/2015-01-01
https://theforexapi.com/api/2015-03-01
https://theforexapi.com/api/2008-01-01

All of them report "Invalid base or symbols".

**Comment by vnmabus** [comment]
Ok, some of them were weekends and that it is fixed now in 71d092272333bff82f5a459b42b7cc266ecef454. The other days are public holidays (https://www.ecb.europa.eu/services/contacts/working-hours/html/index.en.html) and should also be taken into account.

**Comment by coolfire1231** [comment]
Thanks for knowing.Issue is fixed

**Comment by vnmabus** [comment]
I have to say that some dates still not work, but in a different way. For example, https://theforexapi.com/api/2015-01-10 thinks the date requested is 2014-12-31.

**Comment by coolfire1231** [comment]
okay @vnmabus.Will fix the issue ASAP

**Comment by vnmabus** [comment]
Do you have any updates on this one?

**Comment by coolfire1231** [comment]
Hi  @vnmabus ,Sorry for the delay.It's fixed now.and can you check it

**Comment by vnmabus** [comment]
It seems to work now, thank you!
