### ISSUE TITLE
EUR requests returning strings and others returning floats

### ISSUE THREAD

**Issue by abbyjng** [apiforfun/theforexapi#6]
Is it intended for requests with base="EUR" return a rate with a value as a string while all other bases return floats? It seems to make more sense for all bases to return the same rate type. If this should be changed, I can try and write up a PR. If it was intentional, you can disregard and close this issue. Thanks!

**Comment by coolfire1231** [comment]
Thanks for knowing.Issue is fixed

**Comment by lukaszmoroz** [comment]
The problem still persists in historical data, see e.g. https://theforexapi.com/api/2021-06-01/?base=EUR
